### ISSUE TITLE
some kind of suggestion

### ISSUE THREAD

**Issue by Kdy010010** [zeondev/pluto#29]
How about using indexDB on the file system? Then we could save it.

**Comment by Kdy010010** [comment]
also if index DB is supported, we can save other settings like apps, and also using Jekll you can update the app store and can make users upload apps and depoly more easily(this part is without index DB)

**Comment by datkat21** [comment]
The file system is using localForage which uses IndexedDB. We are not using indexedDB by itself due to the complexity it requires, and the localForage library provides a good enough option for storing small and large files together. "Saving" the file system in its current state is more complicated than it seems because of file import links (links to other larger files stored in the localForage's indexed db) which can't simply be exported. The App Store is its own repository [see here](https://github.com/zeondev/Pluto-AppStore) and is handled separately from the file system. I don't think using Jekyll will help with the App Store, or any part of Pluto as there is a lot of client-side JavaScript code that's running.

**Comment by datkat21** [comment]
Closing as this issue appears to be resolved.
